### ISSUE TITLE
Filter based on log level

### ISSUE THREAD

**Issue by alexec** [bensadeh/tailspin#10]
I want to only see ERROR, or WARN, or INFO logs.

Press 1 = only show ERROR
Press 2 = show > WARN
Press 3 = show > INFO
Press 4 = show all

**Comment by alexec** [comment]
https://github.com/kitproj/kit/issues/30

**Comment by bensadeh** [comment]
Hi Alex,

Thanks for trying out tailspin and posting this issue. You bring up a good point on filtering lines for severity levels. It is possible to achieve this today, but I should update the readme with an explanation on how to do it.

In the meantime I'll describe how to do the filtering here. Even though name-wise `tailspin` is a take on `tail`, we are actually using `less` to view the logs files. This is because less comes with a lot of useful functionality like scrollback also filtering while still offering a follow mode like `tail -f`.

If you ran tailspin with the follow flag (`-f`), interrupt (<kbd>Ctrl</kbd> + <kbd>C</kbd>) to stop following for now. From here you can filter through `less` by running the following commands:
- Only show errors: `&ERROR `
- Show warnings and above: `&ERROR|WARNING`
- Show info and above: `&ERROR|WARNING|INFO`
- Show all / reset filtering: `&`

You can now resume following for new entries with <kbd>Shift</kbd> + <kbd>F</kbd>

When it comes to mapping these to keypresses, we are limited by the fact that we view the output through `less`, for better or worse.

**Comment by alexec** [comment]
Cool. Will try
