### ISSUE TITLE
Readling large log files

### ISSUE THREAD

**Issue by koen-serry** [bensadeh/tailspin#108]
Hi, gave tailspin a spin :) and while it works on smaller logfiles and tailing others (or even folders which is great) it seems to have problems with large (>100mb) files. So I think there may be something off with the less pager.

**Comment by bensadeh** [comment]
Hi @koen-serry and thanks for opening this issue.

What version of tailspin are you on and what exactly is the problem you're experiencing when trying to open large files?

If it is to do with performance (slow to open), I released version `2.3.0` less than an hour ago which use multithreading to apply the highlighting. This will speed up the processing for all cases, but will be especially noticeable on larger log files like the one you are viewing.

Note that there will always be some sort of performance impact to opening large files because of the amount of work that is being done on each line (see https://github.com/bensadeh/tailspin/issues/55 for more info).

**Comment by koen-serry** [comment]
Did a checkout just a minute ago with a fresh cargo install and on a large file (5GB) it's taking minutes, whereas when opening with less it's pretty much instant. Forgive my ignorance for not looking yet into the code but could it be that it's highlighting the full file instead of whats visible?

**Comment by bensadeh** [comment]
Thank you for testing with the latest version.

You are correct, `tailspin` highlights the whole file before displaying the contents in `less`.

For this reason, `tailspin` might not be a good fit for very large log files. Perhaps https://github.com/tstack/lnav might be a better fit for your needs if you are working with larger files and are more of a power user.
