### ISSUE TITLE
Add sleep-interval option

### ISSUE THREAD

**Issue by kjgfcdb** [bensadeh/tailspin#119]
Thanks for making this great tool!

I wonder if `tspin` could support the `--sleep-interval=N` option like `tail` command, so that when I use `tspin -f -s 2 log.txt`, the outputs could be more real-time?

**Comment by bensadeh** [comment]
Hi @kjgfcdb and thanks for using tailspin!

Implementing a `--sleep-interval` is not something that would be likely to be added in the near future. However, I made `tailspin` in a way that works well with other unix cli tools so that we can "reuse" the functionality there.

For example, if you find the sleep functionality in the command in `tail` (or other commands), you can just pipe the output of `tail` to `tailspin` like so:

```console
tail [arguments with sleep functionality] | tspin
```
Or, if you want to use `less`:

```console
tspin --listen-command 'tail [arguments with sleep functionality]'
```

Speaking of less, you can always follow and unfollow with F and Ctrl + C.

Are those workaround / alternatives viable for you?

**Comment by kjgfcdb** [comment]
Hi @bensadeh , thanks for your quick reply! I also find this workaround, it really works!

**Comment by bensadeh** [comment]
Glad it worked for you, and happy you find the tool useful 😄
