### ISSUE TITLE
log files in json format

### ISSUE THREAD

**Issue by maku** [bensadeh/tailspin#133]
it would be great when tailspin is able to handle log files in json format

**Comment by bensadeh** [comment]
Thanks for opening this issue @maku ,

json handling is something I have been a bit cautious of getting into, since I've been wanting the scope of `tailspin` to be highlighting regular log files. To understand the use case better, what are you looking for `tailspin` to do with json files that other tools (like `jq`) don't provide today?

**Comment by maku** [comment]
@bensadeh I have an application that generates log data in JSON format (rolling file where the current daily data is logged into a separate file which is then archived in a folder every day). I'm looking for a simple app that can handle this with some kind of aggregation  and present the JSON data and possibly also handle a search. 

The format of the entries in the log file is:

`
{"requestId":"e2770848-0859-4e8d-8348-8ca7717fc5d9","uuid":"14ad72e3-16de-4c0c-ad72-e316de5c0c14","timestamp":"2024-04-08 10:27:31,102","message":"xxxxx","level":"ERROR","thread":"tomcat-handler-384","exception":"xxxx"}
`

 (it is not valid json because the records are not in an array)

**Comment by bensadeh** [comment]
I decided to move away from formatting altogether.

From `4.0.0` `tailspin` will recognize `JSON`s which should help with the formatting and highlighting in general.
