### ISSUE TITLE
name of executable clashes with existing tool

### ISSUE THREAD

**Issue by jonassmedegaard** [bensadeh/tailspin#21]
Hi,

Nice tool.  I am now looking into packaging it for Debian.

One little nit, though: The executable is called "spin" which clashes with [another tool](https://spinroot.com/spin/whatispin.html).

Please consider renaming this tool.  I suggest same name as the project: "tailspin".
In fact, for now I am preparing the Debian package with name changed to "tailspin" because it is not permitted for multiple packages in Debian to provide same name (unless they provide same ABI which clearly this name clash is not an example of).

**Comment by bensadeh** [comment]
Hi Jonas! 

Thank you very much for using tailspin and for looking into packaging it for Debian! I hope we can find a good solution to the naming conflict.

For me personally, I wanted to go with `spin` as the binary name since it was short and simple. It was important for me that the binary name reflected the simplicity of the tool itself.

Would it be possible to rename the binary to `tailspin` as a part of the Debian packaging process? That way binary name would be `tailspin` on Debian (this would be mentioned in the readme) and `spin` for other package managers?

**Comment by jonassmedegaard** [comment]
Yes, there is absolutely no need for you to align with the needs of Debian.  I just thought that you might want a single unified name across distros and directly-installed, and know from experience that it is more painful to rename later.

**Comment by jonassmedegaard** [comment]
another relatively short name not already used within Debian is `tspin`, in case that interests you.

**Comment by bensadeh** [comment]
Thanks for letting me know. It is always a tradeoff of something, I guess 😄 . Lets go with just `tailspin` as the binary for now.

Thank you again for taking the time to do this, really appreciate the help to get tailspin to more package managers 🙏 . I'll update the Readme as soon as it is ready.

**Comment by jonassmedegaard** [comment]
FYI, tailspin has now entered the development branch "unstable" of Debian.
A developer-oriented status page is at https://tracker.debian.org/pkg/tailspin
A more user-oriented page is at https://packages.debian.org/tailspin

**Comment by bensadeh** [comment]
Thank you very much for taking the time to bring this to Debian.

How would a Debian user go about installing this? I can update the readme with the instructions.

**Comment by jonassmedegaard** [comment]
They would issue the command `apt install tailspin`.

**Comment by bensadeh** [comment]
I've updated the Readme with installation instructions.
