### ISSUE TITLE
Performance issues with large files (slow to open)

### ISSUE THREAD

**Issue by johnmaguire** [bensadeh/tailspin#55]
I tested tailspin on a 868M log file (one I routinely check on my system) and it took 2 minutes and 45 seconds to open in tailspin, pegging a core the entire time. This same file opens instantly with less.

I'd love to use tailspin when this is resolved!

**Comment by bensadeh** [comment]
Hi @johnmaguire !

Thank you for trying out `tailspin`! 

Unfortunately, opening up logs in `tailspin` will always come with some performance penalty compared to opening them in `less` due to the amount of work required to apply the highlighting. 

However, as you mention, things can improve a lot if we used more than one core. I will add support for parallelizing the work of applying highlighting, which should improve the performance with large files.

Keep in mind that it will likely not open instantly after the changes, but I hope that the speedup will be useful regardless.

**Comment by johnmaguire** [comment]
@bensadeh Thanks for the reply. I had imagined the primary difference between less and spin is that less doesn't load the entire file into memory before rendering, and spin does - but I haven't inspected spin's source code to validate that that's true. Am I mistaken?

**Comment by bensadeh** [comment]
Yes, almost. Instead of loading it into memory, `tailspin` creates a temporary file with all the highlights applied to it. This means that we are duplicating the file on disk for the duration of the program. On the other hand, it is lightweight on memory after the highlighting has been applied.

My design philosophy with `tailspin` was to try to do one thing (highlighting) well. It is meant to be able to use on its own, but also to be integrated in shell scripting like you would expect. 

If we incorporated our own pager (like `lnav` does), we could optimize it to only apply highlighting to what is on screen, and open the file immediately. However, for the time being, this is not something I am able to do.

`lnav` is a great tool for reading logs, and it is a tool I was aware of when making `tailspin`. Because of `tailspin`'s simplicity in being a highlighter, it would be likely that `lnav` is a better fit for handling certain types of log files.

That being said, I am happy to look into ways to make `tailspin` more accessible and performant within the limitations of the tool if highlighting is all that is needed.

**Comment by johnmaguire** [comment]
Thanks for the response @bensadeh. I've never used lnav in the past, I just saw it mentioned in the HN thread. It looks a little more opinionated and complex than a tool I was hoping to integrate into my workflow.

That being said, the startup time tailspin incurs for large log files unfortunately makes it unusable for my use case. But that doesn't mean you should cater to it!

Thanks for putting tailspin out there!

**Comment by bensadeh** [comment]
I see, and not a problem, thanks for giving `tailspin` a go regardless 😄 . It's always best to use the right tool for the job 💪.

**Comment by bensadeh** [comment]
Hi again @johnmaguire ,

I've just released `2.3.0` where tailspin uses [`rayon`](https://github.com/rayon-rs/rayon) to process lines in parallel using multithreading.

For a 868M log file, it will still take some time, but with the latest changes it should be a lot faster than 2 minutes and 45 seconds.

Anyways, thanks again for giving `tailspin`a shot, and please let me know if any other issues might pop up.
