### ISSUE TITLE
Handle quote escapes inside strings

### ISSUE THREAD

**Issue by rnbguy** [bensadeh/tailspin#61]
Strings such as the following are not appropriately highlighted.

```
"Hello \"World\""
``` 

Steps to reproduce
```sh
echo "\"Hello \\\"Mars\\\"\"" | spin
```

**Comment by bensadeh** [comment]
Hi @rnbguy and thanks for providing steps to reproduce the highlighting. `tailspin` does not currently support escaping the quotes in the strings. The goal of `tailspin` is to highlight human readable logs, and escape characters are therefore not likely to be supported in the future.

It won't directly solve your issue, but we could customize the token which the quotes highlighting is operating on to, for example `'` instead of `"`. 

Otherwise, if you have control over the log output, you could perhaps change some of the quotes tokens to use single quote instead of double quote? Then this line would work:

```console
echo "\"Hello 'Mars'\"" | tspin
```

**Comment by rnbguy** [comment]
> highlight human readable logs, and escape characters are therefore not likely to be supported

Are you saying, String within String would require a nested highlighting, which is difficult?

**Comment by bensadeh** [comment]
The aim of tailspin is to highlight human readable logs. An escape character, on the other hand, is a signal meant for the computer.

For this reason, I’d like to avoid handling those cases.

**Comment by rnbguy** [comment]
Aha. I see your point now. Thanks for explaining. :pray:

**Comment by bensadeh** [comment]
No worries. Thanks for taking the time to try out `tailspin`.
