### ISSUE TITLE
Incorrect formatting

### ISSUE THREAD

**Issue by frakman1** [bensadeh/tailspin#62]
On MacOS 13.1, using iTerm.

When viewing a log file in `nano`, it displays correcly:

<img width="1222" alt="image" src="https://github.com/bensadeh/tailspin/assets/5826484/6e3fc4d0-bdd1-4a7c-b18d-73256f00e54f">

However when viewing it through spin, it looks messed up:

<img width="1223" alt="image" src="https://github.com/bensadeh/tailspin/assets/5826484/151054dc-d5d9-4ec6-b914-736eabcfeaaa">

Similarly when piping the output of `cat`:

<img width="1219" alt="image" src="https://github.com/bensadeh/tailspin/assets/5826484/4f16b45c-9252-42b3-ac2f-b8c253712dff">

**Comment by bensadeh** [comment]
Hi @frakman1 ,

`tailspin` works on a line-by-line basis, which means that it does not know about preceding or succeeding lines. This is by design, as it is a log file highlighter and log entries arrive one line at a time. So if you know for example that your logs are actually `json`s, then a `json` viewer would be a better choice.

There seems to be some issues with encoding here. `\n` is interpreted as a new line, but in your example it looks as this is a raw string.

Can you please provide an example of input / output and what you expect to see? Since we are working on individual lines, you can just :
```console
echo "Example string" | tspin
```

And then we can debug it one line at a time.

**Comment by frakman1** [comment]
I tried `jq` but it looks like this is not valid json either. It's a log file with its own key/value formatting.
The problem is that the Response fields are these massive strings with embedded \n and escape characters before every forward slash e.g. ` <\/propstat>\n        \n<\/response>\n\n\n<\/multistatus>`

Anyway, not sure if `tailspin` can help here. It was just one of the first log files I tried it with.

I also noticed that tailspin would not stop and wait for keyboard input when I tried it with this file. i.e `cat <filename> | spin`  would run through all the way to the end. `cat <filename> | more` would wait for keyboard input.

The log file contains too mcuh sensitive information to redact and try to extract data from so unless you have a copy of the Mac's Fantastical 2 app, I'll close this issue and hope for the best. Thank you for your support!
